{{- if .Values.jigasi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi-meet.jigasi.fullname" . }}
  labels:
    {{- include "jitsi-meet.jigasi.labels" . | nindent 4 }}
  {{- with .Values.jigasi.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  {{- if .Values.jigasi.strategy }}
  strategy: {{- toYaml .Values.jigasi.strategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jitsi-meet.jigasi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jitsi-meet.jigasi.selectorLabels" . | nindent 8 }}
      {{- range $label, $value := mergeOverwrite .Values.global.podLabels .Values.jigasi.podLabels }}
        {{ $label }}: {{ $value }}
      {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/jigasi/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/jigasi/xmpp-secret.yaml") . | sha256sum }}
      {{- range $annotation, $value := mergeOverwrite .Values.global.podAnnotations .Values.jigasi.podAnnotations }}
        {{ $annotation }}: {{ $value|quote }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "jitsi-meet.serviceAccountName" . }}
      securityContext:
        fsGroup: 2000
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.jicofo.securityContext | nindent 12 }}
        image: "{{ .Values.jigasi.image.repository }}:{{ default .Chart.AppVersion .Values.jigasi.image.tag }}"
        imagePullPolicy: {{ pluck "pullPolicy" .Values.jigasi.image .Values.image | first }}
        # {{- with default .Values.jigasi.livenessProbe .Values.jigasi.livenessProbeOverride }}
        # livenessProbe:
        # {{- toYaml . | nindent 10 }}
        # {{- end }}
        # {{- with default .Values.jigasi.readinessProbe .Values.jigasi.readinessProbeOverride }}
        # readinessProbe:
        # {{- toYaml . | nindent 10 }}
        # {{- end }}

        envFrom:
        - secretRef:
            name: {{ include "call-nested" (list . "prosody" "prosody.fullname") }}-jigasi
        - configMapRef:
            name: {{ include "call-nested" (list . "prosody" "prosody.fullname") }}-common
        - configMapRef:
            name: {{ include "jitsi-meet.jigasi.fullname" . }}
        
        resources:
          {{- toYaml .Values.jigasi.resources | nindent 12 }}
{{- end }}