{{$root := .}}

{{- range $i, $jvb := .Values.jvbs }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi-meet.jvb.fullname" $root }}-{{ $i }}
  labels:
    {{- include "jitsi-meet.jvb.labels" $root | nindent 4 }}
    deployment: {{ $i }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "jitsi-meet.jvb.selectorLabels" $root | nindent 6 }}
      deployment: {{ $i }}
  template:
    metadata:
      labels:
        {{- include "jitsi-meet.jvb.selectorLabels" $root | nindent 8 }}
        deployment: {{ $i }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/jvb/configmap.yaml") $root | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/jvb/xmpp-secret.yaml") $root | sha256sum }}
    spec:
      {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jitsi-meet.serviceAccountName" $root }}
      securityContext:
        {{- toYaml $root.Values.jvb.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $root.Chart.Name }}
          securityContext:
            {{- toYaml $root.Values.jvb.securityContext | nindent 12 }}
          image: "{{ $root.Values.jvb.image.repository }}:{{ default $root.Chart.AppVersion $root.Values.jvb.image.tag }}"
          imagePullPolicy: {{ pluck "pullPolicy" $root.Values.jvb.image $root.Values.image | first }}
          envFrom:
          - secretRef:
              name: {{ include "call-nested" (list $root "prosody" "prosody.fullname") }}-jvb
          - configMapRef:
              name: {{ include "call-nested" (list $root "prosody" "prosody.fullname") }}-common
          - configMapRef:
              name: {{ include "jitsi-meet.jvb.fullname" $root }}
          env:
          - name: DOCKER_HOST_ADDRESS
            value: {{ first $jvb.publicIPs }}
          - name: JVB_ADVERTISE_IPS
            value: '{{ $jvb.publicIPs | join "," }}'
          {{- if $root.Values.websockets.colibri.enabled }}
          - name: JVB_WS_SERVER_ID
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          {{- end }}
          {{- if  $root.Values.octo.enabled }}
          - name: JVB_OCTO_BIND_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: JVB_OCTO_PUBLIC_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          {{- end }}
          ports:
            - name: rtp-udp
              containerPort: {{ $root.Values.jvb.UDPPort }}
              {{- if $root.Values.jvb.useHostPort }}
              hostPort: {{ $root.Values.jvb.UDPPort }}
              {{- end }}
              protocol: UDP
          {{- if or $root.Values.websockets.colibri.enabled }}
            - name: colibri-ws-tcp
              containerPort: 9090
              protocol: TCP
          {{- end }}
          {{- with $root.Values.jvb.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $root.Values.jvb.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml $root.Values.jvb.resources | nindent 12 }}

        {{- if $root.Values.jvb.metrics.enabled }}
        - name: metrics
          image: {{ $root.Values.jvb.metrics.image.repository }}:{{ $root.Values.jvb.metrics.image.tag }}
          imagePullPolicy: {{ $root.Values.jvb.metrics.image.pullPolicy }}
          securityContext:
            runAsUser: 10001
          command:
            - /prometheus-jitsi-meet-exporter
            - -videobridge-url
            - http://localhost:8080/colibri/stats
          ports:
            - containerPort: 9888
              name: tcp-metrics
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 9888
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
        {{- toYaml $root.Values.jvb.metrics.resources | nindent 12 }}
        {{- end }}

      {{- with $root.Values.jvb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or $root.Values.jvb.affinity }}
      affinity:
        {{- toYaml $root.Values.jvb.affinity | nindent 8 }}
      {{- end }}
      {{- with $root.Values.jvb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end}}