{{$root := .}}

{{- range $i, $jvb := .Values.jvbs }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.jvb.fullname" $root }}-{{ $i }}
  annotations:
  {{- range $key, $value := $root.Values.jvb.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
    metallb.universe.tf/loadBalancerIPs: {{ $jvb.loadBalancerIP }}
  labels:
    {{- include "jitsi-meet.jvb.labels" $root | nindent 4 }}
    deployment: {{ $i }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ default 10000 $root.Values.jvb.UDPPort }}
      protocol: UDP
      name: rtp-udp
  selector:
    {{- include "jitsi-meet.jvb.selectorLabels" $root | nindent 4 }}
    deployment: {{ $i }}
---
{{- end}}