{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    kubernetes.io/tls-acme: "true"
  labels: {{- include "labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "basename" . }}
            port:
              number: 80
        path: /
        pathType: Prefix
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ .Values.ingress.hostname }}
  {{- end}}
{{- end}}
